datawire/emojivoto

- Dockerfile
- Dockerfile-ui
- Makefile
- common.mk
- emojivoto-web-app/.env
- emojivoto-web-app/js/components/Leaderboard.jsx
- emojivoto-web-app/js/components/Vote.jsx
- web-app-nginx.conf
This PR adds a proxy on the nginx server to redirect the traffic to the backend located on the cluster.
> Fix communication between frontend and backend on the cluster

- emojivoto-web-app/js/components/Leaderboard.jsx
- emojivoto-web-app/js/components/Vote.jsx
> remove footer

- Dockerfile
- common.mk
- docker-compose.yml
- emojivoto-web/cmd/server.go
- emojivoto-web/web/web.go
- kustomize/deployment/emoji.yml
- kustomize/deployment/vote-bot.yml
- kustomize/deployment/voting.yml
- kustomize/deployment/web.yml
- manifests/apps_v1_deployment_emoji.yaml
- manifests/apps_v1_deployment_voting.yaml
- manifests/apps_v1_deployment_web.yaml
- manifests/argoproj.io_v1_rollout_web-app.yaml
This PR implements the logic to propagate the "x-telepresence-intercept-id" header to the voting grpc service.
> Add logic to send intercept header to the voting grpc service

- .github/workflows/publish.yaml
- emojivoto-web/Makefile
- emojivoto-web/web/web.go
So when the user intercept with telepresence it can see it running on
his local machine.
Also create a release with the `emojivoto-server` binaries when a tag is created.
> 🔊 Add logging to requests

- emojivoto-web-app/js/setup_dev_env.sh
* Also, check that docker is installed.
Example output:
```console
❯ ./setup_dev_env.sh 
Step 1/7: Checking required tools
Step 2/7: Checking for AMBASSADOR_API_KEY environment variable
Step 3/7: Configuring development container. This container encapsulates all the dependencies needed to run the emojivoto-web-app locally.
This may take a few moments to download and start.
b9656be55ba71d240753b62606c6b0a74bb0866f7634ecf5001ebadd638560d9
latest: Pulling from datawire/emojivoto-node-and-go-demo
Digest: sha256:cce2c335545f9f23215243c245cface81c05078215bfd24e49ca8a0a6ae65621
Status: Image is up to date for datawire/emojivoto-node-and-go-demo:latest
Step 4/7: Extracting KUBECONFIG from container
.
Listing services in emojivoto namespace
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP …
```
> Add more output to setup dev script

- emojivoto-web-app/js/setup_dev_env.sh
Show the user the progress on the docker run command so if it drag,
the user can see why.
> Silent the script when we check for the demo container running

- emojivoto-web-app/js/setup_dev_env.sh
to add segment to the script:
```console
./setup_dev_env.sh segment-1
```
If no arg provided, segment will be ""
> Add segment to setup_dev_env.sh script for metrics

- emojivoto-web-app/js/setup_dev_env.sh
In the docker command, remove volume map to host config and network
capacity.
Instead of getting the KUBECONFIG file from container the KUBECONFIG is
downloaded directly to local machine.
Add telepresence quit and connect before the intercept.
> Change docker image to use

- emojivoto-web-app/js/setup_dev_env.sh
Move the `telepresence connect` after we perform the `telepresence login` otherwise it could cause some friction points
> Perform login before to connect

- emojivoto-web-app/js/setup_dev_env.sh
> Update TP version in script

- emojivoto-web-app/js/setup_dev_env.sh
Update the web-app in the setup script
> change web-app for intercept

- emojivoto-web-app/css/styles.css
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade Telepresence to version 2.7.1 from 2.6.8
> Upgrade telepresence to version 2.7.1

- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.13.2
> Upgrade telepresence to 2.13.2

- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.13.3
> Upgrade telepresence to 2.13.3

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.14.0
> Upgrade telepresence to 2.14.0

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.14.1
> Upgrade telepresence to 2.14.1

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.14.2
> Upgrade telepresence to 2.14.2

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.14.4
> Upgrade telepresence to 2.14.4

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.15.0
> Upgrade telepresence to 2.15.0

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.15.1
> Upgrade telepresence to 2.15.1

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
⚠️ This PR must be merged only when telepresence 2.16 is released ⚠️
> Update connect command to align with Telepresence 2.16 changes

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.16.0
> Upgrade telepresence to 2.16.0

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.16.1
> Upgrade telepresence to 2.16.1

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.17.0
> Upgrade telepresence to 2.17.0

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.17.1
> Upgrade telepresence to 2.17.1

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.18.0
> Upgrade telepresence to 2.18.0

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.18.1
> Upgrade telepresence to 2.18.1

- emojivoto-web-app/js/setup_dev_env.ps1
- emojivoto-web-app/js/setup_dev_env.sh
Upgrade telepresence to 2.19.0
> Upgrade telepresence to 2.19.0
